### ISSUE TITLE
Add a custom theme for CodesHub website

### ISSUE THREAD

**Issue by devxprite** [diwas7777/CodesHub#203]
I want to add a custom theme for CodesHub website like this:

![codeshub](https://user-images.githubusercontent.com/80192140/197135200-5bc46a04-d81a-4bb0-81ba-3cdfc6e74543.png)

**Preview:** https://devxprite.github.io/CodesHub/

**Comment by ghost** [comment]
yes you can but please remove space between Codes and Hub and make it CodesHub without spacing

**Comment by ghost** [comment]
please do a PR for that and I will accept it :)
