### ISSUE TITLE
Code snippets

### ISSUE THREAD

**Issue by shawshankkumar** [diwas7777/CodesHub#47]
Hey, 

I am planning on making multiple micro PRs. I am well-versed in Java, JavaScript, TypeScript and Python. So I am intending on making 2 PRs for JavaScript and TypeScript Code snippets which I use very frequently. One is validation using Yup and a proper function for that, another is a lodash demo and comparison. 

The other 2 will be Go code snippets, since I am just learning Go, I will either make a simple API or a function. 

Does that work? I want to contribute something which I have learnt or will learn and leave behind a code snippet for others. 

Maybe I will try out zod with typescript. Is that fine and will that be accepted?

**Comment by ghost** [comment]
yes it is fine as long as it follows our code of conduct

**Comment by shawshankkumar** [comment]
Great. Thanks!

**Comment by shawshankkumar** [comment]
I will close this and raise a PR in few.

**Comment by ghost** [comment]
okay
