### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by ghost** [diwas7777/CodesHub#97]
Can anyone help me make a website for this github project?

**Comment by Amank-root** [comment]
Hi, @diwas777777 what type of website you are talking about?

**Comment by ghost** [comment]
> Hi, @diwas777777 what type of website you are talking about?

website where users can have easy access to codes in this github repo 

Folders will be categories

**Comment by yogesh-9999** [comment]
Hey @diwas777777  assign it to me

**Comment by ghost** [comment]
> Hey @diwas777777 assign it to me

Assigned

**Comment by ghost** [comment]
> Hey @diwas777777 assign it to me

@yogesh-9999 are you going to do it?

**Comment by ghost** [comment]
need confirmation

**Comment by Harsh-raj-x07** [comment]
Hey @Amank-root can you assign me?

**Comment by ghost** [comment]
@Harsh0326 will you help me make website?

**Comment by Harsh0326** [comment]
Yes

**Comment by Harsh-raj-x07** [comment]
> @Harsh0326 will you help me make website?

Yes

**Comment by ghost** [comment]
@Harsh0326 i am assigning you

**Comment by ghost** [comment]
@Harsh0326 Please wait for a while I am currently having dinner so will check your PR for website in a while

**Comment by Harsh-raj-x07** [comment]
> @Harsh0326 Please wait for a while I am currently having dinner so will check your PR for website in a while

Ok ! Pls assign me

**Comment by Harsh-raj-x07** [comment]
> > @Harsh0326 Please wait for a while I am currently having dinner so will check your PR for website in a while
> 
> Ok ! Pls assign me

It’s my first time contribution…………I hope you understand 🙌🏼

**Comment by ghost** [comment]
okay

**Comment by ghost** [comment]
The prerequisities for website is that it should have a home page and there should be search bar in it through which one can search for code.
Searching should show all the pages that matches users input for user to choose

code page should be editable for admin
admin could add code in code section and description about how  it works in Description section in the page

for now that's it

**Comment by ghost** [comment]
> The prerequisities for website is that it should have a home page and there should be search bar in it through which one can search for code. Searching should show all the pages that matches users input for user to choose
> 
> code page should be editable for admin admin could add code in code section and description about how it works in Description section in the page
> 
> for now that's it

@Harsh0326

**Comment by ghost** [comment]
@Harsh0326 if you are not interested in website then you can contribute to repo in some other ways for that please read README.md file
